### ISSUE TITLE
能否分享下阿里云部分的项目

### ISSUE THREAD

**Issue by EmilyZ-t** [flwfdd/MergeMusic#1]
您好，我最近刚学前端，想用网易云音乐做一个类似于网易云音乐界面的网页，您的html现在是可以正常运行但是我怕，您阿里云到期我还没开发完，所以您能否分享阿里云部分的项目代码？

**Comment by flwfdd** [comment]
抱歉一直没看到(＠_＠;)，现在已经分享了（虽然已经过去两年了2333
