### ISSUE TITLE
版权风险提醒

### ISSUE THREAD

**Issue by jsososo** [flwfdd/MergeMusic#3]
在 B站 刷到了这个网站的推荐视频，这里提醒一下，如果想要分享，不要用国内备案的网站。我自己之前的音乐网站就是国内备案，然后被王杰团队举报侵权（虽然那首歌在网易云是免费的），然后投诉到的是中宣部，再被地方文化局约谈的

**Comment by flwfdd** [comment]
好的，感谢提醒

**Comment by VictoireWood** [comment]
> 好的，感谢提醒

UP的视频好像已经没了，我在B站首页刷到了但是点进去的时候显示视频不存在。

**Comment by flwfdd** [comment]
> > 好的，感谢提醒
> 
> UP的视频好像已经没了，我在B站首页刷到了但是点进去的时候显示视频不存在。

「已锁定 根据《中华人民共和国著作权法》和《计算机软件保护条例》规定，bilibili禁止发布破解的软件和硬件」(=￣ω￣=)
