### ISSUE TITLE
建议新弹窗使用a标签

### ISSUE THREAD

**Issue by Bylx666** [flwfdd/MergeMusic#4]
使用弹出式窗口是个很影响体验的行为（？）建议改用a标签并设置target标签

**Comment by Bylx666** [comment]
加油！随手star了😋

**Comment by flwfdd** [comment]
我一直用IDM会拦截下载所以没注意🤣
非同源用a标签的话音乐和图片浏览器还是会默认打开，前端下载Blob的话又更复杂了....暂时就先还是这样吧....?不过还是感谢建议！有什么问题欢迎提出~
